"""create initial tables

Revision ID: e1d23dad8974
Revises:
Create Date: 2026-08-28 01:02:23.504389

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "e1d23dad8974"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "region",
            sa.Enum(
                "CAPITAL", "CHUNGCHEONG", "GANGWON", "YEONGNAM", "HONAM", name="region"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "trains",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "train_type", sa.Enum("KTX", "SRT", "ITX", name="traintype"), nullable=False
        ),
        sa.Column(
            "train_number", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False
        ),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("train_type", "train_number", name="uq_train_type_number"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "hashed_password",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("role", sa.Enum("USER", "ADMIN", name="userrole"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "seats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("train_id", sa.Integer(), nullable=False),
        sa.Column(
            "seat_number", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False
        ),
        sa.Column(
            "seat_class", sa.Enum("STANDARD", "FIRST", name="seatclass"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["train_id"],
            ["trains.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("train_id", "seat_number", name="uq_train_seat"),
    )
    op.create_table(
        "train_schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("train_id", sa.Integer(), nullable=False),
        sa.Column("departure_station_id", sa.Integer(), nullable=False),
        sa.Column("arrival_station_id", sa.Integer(), nullable=False),
        sa.Column("departure_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("arrival_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "departure_station_id <> arrival_station_id",
            name="ck_schedule_different_stations",
        ),
        sa.CheckConstraint(
            "departure_time < arrival_time", name="ck_schedule_time_order"
        ),
        sa.ForeignKeyConstraint(
            ["arrival_station_id"],
            ["stations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["departure_station_id"],
            ["stations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["train_id"],
            ["trains.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reservations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=False),
        sa.Column("seat_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "CONFIRMED", "CANCELLED", name="reservationstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["train_schedules.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seat_id"],
            ["seats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_active_schedule_seat",
        "reservations",
        ["schedule_id", "seat_id"],
        unique=True,
        postgresql_where=sa.text("status != 'CANCELLED'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_active_schedule_seat",
        table_name="reservations",
        postgresql_where=sa.text("status != 'CANCELLED'"),
    )
    op.drop_table("reservations")
    op.drop_table("train_schedules")
    op.drop_table("seats")
    op.drop_table("users")
    op.drop_table("trains")
    op.drop_table("stations")
    # ### end Alembic commands ###
